// API
export const API_CONFIGURE = 'AR_API_CONFIGURE';

// REMOTE
export const REMOTE_CLEAR = 'AR_REMOTE_CLEAR';
export const REMOTE_HYDRATE = 'REMOTE_HYDRATE';

export const REMOTE_WILL_READ = 'AR_REMOTE_WILL_READ';
export const REMOTE_READ_DONE = 'AR_REMOTE_READ_DONE';
export const REMOTE_READ_FAILED = 'AR_REMOTE_READ_FAILED';

export const REMOTE_WILL_CREATE = 'AR_REMOTE_WILL_CREATE';
export const REMOTE_CREATE_DONE = 'AR_REMOTE_CREATE_DONE';
export const REMOTE_CREATE_FAILED = 'AR_REMOTE_CREATE_FAILED';

export const REMOTE_WILL_UPDATE = 'AR_REMOTE_WILL_UPDATE';
export const REMOTE_UPDATE_DONE = 'AR_REMOTE_UPDATE_DONE';
export const REMOTE_UPDATE_FAILED = 'AR_REMOTE_UPDATE_FAILED';

export const REMOTE_WILL_DELETE = 'AR_REMOTE_WILL_DELETE';
export const REMOTE_DELETE_DONE = 'AR_REMOTE_DELETE_DONE';
export const REMOTE_DELETE_FAILED = 'AR_REMOTE_DELETE_FAILED';
