export const API_CONFIGURE = 'AR_API_CONFIGURE';
export const API_CLEAR = 'AR_API_CLEAR';
export const API_HYDRATE = 'API_HYDRATE';

export const API_WILL_READ = 'AR_API_WILL_READ';
export const API_READ_DONE = 'AR_API_READ_DONE';
export const API_READ_FAILED = 'AR_API_READ_FAILED';

export const API_WILL_CREATE = 'AR_API_WILL_CREATE';
export const API_CREATE_DONE = 'AR_API_CREATE_DONE';
export const API_CREATE_FAILED = 'AR_API_CREATE_FAILED';

export const API_WILL_UPDATE = 'AR_API_WILL_UPDATE';
export const API_UPDATE_DONE = 'AR_API_UPDATE_DONE';
export const API_UPDATE_FAILED = 'AR_API_UPDATE_FAILED';

export const API_WILL_DELETE = 'AR_API_WILL_DELETE';
export const API_DELETE_DONE = 'AR_API_DELETE_DONE';
export const API_DELETE_FAILED = 'AR_API_DELETE_FAILED';
